# Generated by Django 3.0.5 on 2020-05-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastername', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rng', models.CharField(max_length=10)),
                ('leastcount', models.CharField(max_length=10)),
                ('uncertainity', models.CharField(max_length=10)),
                ('idno', models.CharField(max_length=10)),
                ('srno', models.CharField(max_length=10)),
                ('calibrationdate', models.CharField(max_length=15)),
                ('calibrationduedate', models.CharField(max_length=15)),
                ('certificateno', models.CharField(max_length=50)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.lab')),
            ],
        ),
    ]
